---
title: "Baseline_characteristics - ITS cohort"
author: "Yamina Boukari / Claire Zhang"
date: "`r Sys.Date()`"
output: 
  word_document:
    reference_docx: reference_table_doc.docx
---

```{r setup, include=FALSE, quiet = TRUE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Baseline characteristics

```{r echo=FALSE, message = FALSE, quiet=TRUE, warning=FALSE}

# Load packages ----
if (!require('pacman')) install.packages('pacman')
pacman::p_load(tidyverse,lubridate, Hmisc, epitools, data.table, epiR, flextable,
               gtsummary)

# Set working directory ----
setwd("filepath")

# Load data ---- 

load(file = "filepath")
load(file = "filepath")

# Functions ----
calc_age <- function(birthDate, refDate = Sys.Date()) {
  require(lubridate)
  period <- as.period(interval(birthDate, refDate),unit = "year")
  period$year
}

# Drop levels that are not needed
matched_its_cohort <- droplevels(matched_its_cohort)
matched_its_annual_records <- droplevels(matched_its_annual_records)

# Create year_cohort_entry, age_cohort_exit and age_cohort_entry variables -----

## Cohort
matched_its_cohort <- matched_its_cohort %>%
  mutate(year_cohort_entry  = year(cohort_entry), 
         age_cohort_entry = calc_age(dob, cohort_entry),
         age_cohort_exit = calc_age(dob, cohort_exit),
         time_ds_to_ce = as.numeric((as.Date(cohort_entry)- as.Date(data_start))/365))
matched_its_cohort$year_cohort_entry <- as.factor(matched_its_cohort$year_cohort_entry)

# Make studyyear a factor in annual files ----

## Full cohort
matched_its_annual_records$studyyear <- as.factor(matched_its_annual_records$studyyear)

# Make tables ----

## Migrant_status 
table1 <- matched_its_cohort %>%
  dplyr::select(migrant_status, total_pyears, gender, year_cohort_entry, age_cohort_entry, age_cohort_exit, time_ds_to_ce, ethnicat6, prac_region, imd) %>%
  tbl_summary(digits = list(all_categorical() ~ c(0,1)), 
              type = c(total_pyears, age_cohort_entry, age_cohort_exit, time_ds_to_ce) ~ 'continuous2', 
              by = migrant_status, 
              statistic = list(total_pyears= c("{sum}", "{mean} ({sd})", "{median} ({IQR})"), 
                               age_cohort_entry = c('{mean} ({sd})', '{median} ({IQR})'), 
                               age_cohort_exit = c('{mean} ({sd})', '{median} ({IQR})'),
                               time_ds_to_ce = c('{mean} ({sd})', '{median} ({IQR})')), 
              percent = 'column',
              label = list(total_pyears ~ 'Total follow up, person-years', 
                           gender ~ 'Sex, n (%)', 
                           year_cohort_entry ~ 'Year of cohort entry, n (%)', 
                           age_cohort_entry ~ 'Age at cohort entry, years', 
                           age_cohort_exit ~ 'Age at cohort exit, years',
                           time_ds_to_ce ~ 'Time from database entry to cohort entry, years',
                           ethnicat6 ~ 'Ethnicity, n (%)', 
                           prac_region ~ 'Practice region, n (%)', 
                           imd ~ 'IMD, n (%)')) %>%
  add_overall() %>%
  modify_footnote(update = everything() ~NA) %>%
  modify_header(update = all_stat_cols(FALSE) ~ "{level}, {n} ({style_percent(p, digits = 1)}%)")

table1b <- matched_its_annual_records %>%
  dplyr::select(migrant_status, studyyear) %>%
  tbl_summary(digits = list(all_categorical() ~ c(0,1)), by = migrant_status,
              label = studyyear ~ 'Patients in each study year, n (%)')%>%
  add_overall() %>%
  modify_footnote(update = everything() ~NA)%>%
  modify_header(update = all_stat_cols(FALSE) ~ "{level}\ n={n} ({style_percent(p, digits = 1)}%)")


merged_table_migrant_status <- tbl_stack(tbls = list(table1, table1b)) # fc = full cohort

# Migcertainty 
table2 <- matched_its_cohort %>% 
  dplyr::select(migcertainty, total_pyears, gender, year_cohort_entry, age_cohort_entry, age_cohort_exit, time_ds_to_ce, ethnicat6, prac_region, imd) %>%
  filter(migcertainty %in% c('Definite', 'Probable')) %>%
  droplevels() %>%
  tbl_summary(digits = list(all_categorical() ~ c(0,1)), 
              type = c(total_pyears, age_cohort_entry, age_cohort_exit, time_ds_to_ce) ~ 'continuous2', 
              by = migcertainty, 
              statistic = list(total_pyears= c("{sum}", "{mean} ({sd})", "{median} ({IQR})"), 
                               age_cohort_entry = c('{mean} ({sd})', '{median} ({IQR})'), 
                               age_cohort_exit = c('{mean} ({sd})', '{median} ({IQR})'),
                               time_ds_to_ce = c('{mean} ({sd})', '{median} ({IQR})')), 
              percent = 'column',
              label = list(total_pyears ~ 'Total follow up, person-years', 
                           gender ~ 'Sex, n (%)', 
                           year_cohort_entry ~ 'Year of cohort entry, n (%)', 
                           age_cohort_entry ~ 'Age at cohort entry, years', 
                           age_cohort_exit ~ 'Age at cohort exit, years',
                           time_ds_to_ce ~ 'Time from database entry to cohort entry, years',
                           ethnicat6 ~ 'Ethnicity, n (%)', 
                           prac_region ~ 'Practice region, n (%)', 
                           imd ~ 'IMD, n (%)')) %>%
  modify_footnote(update = everything() ~NA)%>%
  modify_header(update = all_stat_cols(FALSE) ~ "{level}\ n={n} ({style_percent(p, digits = 1)}%)")


table2b <- matched_its_annual_records %>%
  dplyr::select(migcertainty, studyyear) %>%
  filter(migcertainty %in% c('Definite', 'Probable')) %>%
  droplevels() %>%
  tbl_summary(digits = list(all_categorical() ~ c(0,1)), by = migcertainty,
              label = studyyear ~ 'Patients in each study year, n (%)')%>%
  modify_footnote(update = everything() ~NA)%>%
  modify_header(update = all_stat_cols(FALSE) ~ "{level}\ n={n} ({style_percent(p, digits = 1)}%)")

merged_table_migcertainty <- tbl_stack(tbls = list(table2, table2b))

# Merge migrant_status and migcertainty tables
all_cohorts <- tbl_merge(tbls = list(merged_table_migrant_status, merged_table_migcertainty)) %>%
  modify_spanning_header(everything() ~ NA_character_)


baseline_characteristics <- as_flex_table(all_cohorts)
baseline_characteristics <- flextable::align(baseline_characteristics, align = 'center', part = 'header')%>%
  flextable::set_table_properties(layout = 'autofit')

baseline_characteristics

```


